### PR TITLE
Add support for running via ssh

### PR DESCRIPTION
**Pull request by TravonteD**
- Add installable dependency `gum`
- Update shebang to use `env`
- Update wording for prompt for swapiness "1" -> "yes"
- Formatting updates from `shellcheck`

### CODE REVIEW

**Comment by TravonteD** [comment]
The debugging messages still show for now. How do we want to handle these?

**Comment by CryoByte33** [comment]
@TravonteD I hesitate to disable them completely in case it's needed for troubleshooting. Maybe we can tee them out to a log file in ~/.cryo_utilities?

Also, excellent work thus far. I just checked the code and it looks solid. You've ended up crossing like 3 things off of my to-do list 😂

**Comment by TravonteD** [comment]
I'm down to `tee` to a logfile. Does it make sense to have all of the output go there? The user doesn't necessarily need to see it unless something unexpected occurs.

**Comment by CryoByte33** [comment]
That's true, I guess I'm biased towards providing more data than less, but it might worry users 🤔 I guess that we could redirect all output as well.

Also, I updated the main branch, would you mind rebasing prior to the merge?

**Comment by CryoByte33** [comment]
@TravonteD any updates on this? I'm going to work on some additional functionality soon 🙂

**Comment by TravonteD** [comment]
I plan to wrap this up today. Got sidetrack with the 9-5 :)

**Comment by TravonteD** [comment]
@CryoByte33 I've moved everything to the main function to avoid having redirection all over the place. It now logs stdout to a logfile located in the installation directory.

**Comment by ashl1** [comment]
I see merge conflicts. @TravonteD could you actualize the code?

**Comment by CryoByte33** [comment]
This shouldn't need to exist with the latest version. Thank you for the work, sorry that I restructured the entire project!

**Pull request closed without merging**
