### PR TITLE
fix: small code style improvements

### PR DESCRIPTION
**Pull request by x1unix**
This MR contains small code style improvements that don't affect the app's functionality but improve code readability.

## Noticeable changes:

* Use `switch` instead of if-else-if chains
* Preallocate slice capacity when size is known
* Replace if-else in error handling with early return/continue
* Format Go imports in a few files

## Additional recommendations

Few points that can be added in further PRs:

* Remove code duplication in `main.go` and `ui_util.go`
* Increase unit test coverage for utility functions
* Add `golangci-lint` linter
* Run unit tests and linter using GitHub Actions ([example](https://github.com/x1unix/go-playground/blob/master/.github/workflows/pull_request.yml))

### CODE REVIEW

**Comment by x1unix** [comment]
@CryoByte33 can you please take a look 🙏

**Comment by CryoByte33** [comment]
I saw this but I'm definitely pretty behind on merges considering all the stuff currently going on, I'll try to get to it ASAP.

Thank you for contributing!

**Comment by CryoByte33** [comment]
Sorry for the HUGE delay on this, my life is finally settled to where I can think about CU again. I've reviewed the code itself and it looks great, thank you for untangling the spaghetti a little bit 😉

Have you tested all functionality with these changes?

**Comment by x1unix** [comment]
@CryoByte33 just built my branch and checked on a real Steam Deck. Reverted to stock settings and reapplied the Recommended Settings - seems to be working :)

Screenshot_20231010_162614

**Comment by x1unix** [comment]
Hi @CryoByte33, did you have an opportunity to take a look?

Thank you.

**Pull request merged**
