### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by CalebQ42**
Your Youtube video pop-up for me and I decided to take a look since I have a decent amount of experience with Go.

- Small changes suggested by the linter. Mostly just field alignment and unused variables
- Replaced instances of `fmt.Sprintf` to join filepaths to `filepath.Join`
- Removed several instances of deferred functions that's purpose was to catch a `.Close()` error. Very few libraries actually make use of `io.Closer`'s error return and it's usually safe to ignore it.
  - As an example an `*os.File`'s `.Close()` will only ever return an error if it's already been closed.
- Reworked how sending input to commands for sudo authentication worked.
  - Instead of using a goroutine, it's better to start the command, send the input, and wait for the command to exit on it's own. I also just added a `\n` instead of manually closing the stdin pipe.

### CODE REVIEW

**Comment by CryoByte33** [comment]
Oh wow, thank you! I don't have time to review this at the moment, but I'll try to do so in the next day or so.

Have you been able to build and test it on your Deck? I'd like to make sure it's rock solid before swapping a core function like authentication.

**Comment by CalebQ42** [comment]
👍No rush. I did some unit tests on my laptop, but I'll test it on my deck when I get the chance.

**Comment by CryoByte33** [comment]
Did you ever get a chance to test on Deck? I don't have time this evening, but I'll do it tomorrow morning for sure 🙂

**Comment by CalebQ42** [comment]
Just checked it and everything is working. That being said I don't think think you ever check if the password actually works, I'll see if I can figure that out real quick.

**Comment by CryoByte33** [comment]
I did in the previous version [here](https://github.com/CryoByte33/steam-deck-utilities/blob/main/internal/ui_authentication.go#L48). The sudo command itself tests for auth by providing an error code if it fails.

**Comment by CalebQ42** [comment]
All working now.

**Comment by CryoByte33** [comment]
I can't believe I missed the missing # in the launcher, thank you for picking up on that. I'll test your changes first thing in the morning and merge as long as it looks good.

Thank you again for the outstanding work!

**Comment by CryoByte33** [comment]
Getting an error on build:
```
internal/ui_authentication.go:16:6: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
internal/ui_authentication.go:52:6: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
[✗] exit status 2
```

**Comment by CalebQ42** [comment]
'cmd.WaitDelay' was added in 1.20, so I'm guessing you're still on 1.19.

**Comment by CryoByte33** [comment]
> 'cmd.WaitDelay' was added in 1.20, so I'm guessing you're still on 1.19.

I didn't realize 1.20 came out, shows how long I've been working on this. Updating and testing now!

**Comment by CryoByte33** [comment]
Alright, before merge I need you to change the go version in go.mod to 1.20 (which was my issue). I'll be happy to merge it right after!

**Comment by CalebQ42** [comment]
There you go!

**Comment by CryoByte33** [comment]
Perfect, you rock.

**Pull request merged**
